### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by nstoeckigt** [MonDiscourse/discourse-formatting-toolbar#3]
Toolbar v2.3
Discourse (currently 1.9.0 b7) 1.8.x

Since an update to 1.8.x (not entirely sure which exact version) the toolbar is no longer displayed and used formatings are shown as raw (e.g.  [u]underline[/u] ).

Feel free to ask vor additional info!

**Comment by ghost** [comment]
You can't upgrade to the latest version of Discourse ? (With some customized plugins, I know it can be hard to upgrade Discourse)

The markdown engine changed completely since then and I had to upgrade the plugin. I could create a branch with the former version if you really can't upgrade Discourse

If you're familiar with github, you can download the compatible version here : https://github.com/iunctis/discourse-formatting-toolbar/tree/e41246fe280f577e9740877ee5439772d2f19e66
And add the plugin on you github too.

**Comment by ghost** [comment]
I've created a branch

You'll just have to change your app.yml where you cloned this plugin to put : 

`- git clone --branch old-markdown https://github.com/iunctis/discourse-formatting-toolbar.git`

It should work, but I'm not the biggest expert of these branches and github

**Comment by nstoeckigt** [comment]
I didn't use your branch, instead we have a testing environment were I installed the latest Discourse beta - still not working. ...probably it's some interference with other plugins - Do you know some issues in this direction?

**Comment by ghost** [comment]
This plugin can have some issues with discourse-bbcode for example. What plugins do you have ?

**Comment by nstoeckigt** [comment]
I use a plugin of my own which highly is build upon discourse-bbcode. I'll try to disable or remove it and check the behavior.

Thanks for your help so far!  :)
